name: wampshell
base: core24
version: git
summary: Command-line utilities for WAMP Shell
description: |
  WAMP Shell is a peer-to-peer and routed shell environment.
  This snap package provides the command-line utilities for it.

grade: stable
confinement: strict
compression: lzo

plugs:
  dot-wampshell:
    interface: personal-files
    write:
      - $HOME/.wampshell

parts:
  wampshell:
    plugin: go
    source: .
    build-snaps:
      - go
    build-packages:
      - git

apps:
  wsh:
    command: bin/wsh
    plugs:
      - network
      - dot-wampshell

  wsh-keygen:
    command: bin/wsh-keygen
    plugs:
      - dot-wampshell

  wcp:
    command: bin/wcp
    plugs:
      - network
      - home
      - dot-wampshell
